feat: Implement GlanceNoOpImpl in debug mode

diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -35,17 +35,21 @@ jobs:
           git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
       - name: Check releasing
         run: | # Ensure we can run release-it successfully after merged
-          release-it ${{ inputs.version }} \
-            --no-git.commit \
-            --'git.commitMessage="Release ${version}"' \
+          output=$(release-it "${{ inputs.version }}" \
             --git.tag \
-            --'git.tagName="${version}"' \
-            --'git.tagAnnotation="Release ${version}"' \
+            --git.tagName="${version}" \
+            --git.tagAnnotation="Release ${version}" \
             --git.push \
             --github.release \
             --no-github.web \
             --ci \
-            --dry-run
+            --dry-run)
+
+          # Check if the output contains "ERROR"
+          if echo "$output" | grep -q "ERROR"; then
+            echo "ERROR: The environment cannot successfully run release-it. Please check the environment configuration."
+            exit 1
+          fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Run release-it
